version: 1
formatters:
  simple:
    format: '%(asctime)s|%(process)d|%(name)s|%(levelname)s|%(message)s'
    datefmt: '%d.%mT%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
app:
  level: DEBUG
  handlers: [console]