# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 944)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("QLCDNumber { \n"
"    color: red;\n"
"    background-color: rgb(204, 219, 162);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1291, 481))
        self.widget.setObjectName("widget")
        self.kinect_group = QtWidgets.QHBoxLayout(self.widget)
        self.kinect_group.setContentsMargins(0, 0, 0, 0)
        self.kinect_group.setObjectName("kinect_group")
        self.kinect_video_widget = QtWidgets.QWidget(self.widget)
        self.kinect_video_widget.setObjectName("kinect_video_widget")
        self.kinect_video = QtWidgets.QLabel(self.kinect_video_widget)
        self.kinect_video.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.kinect_video.setObjectName("kinect_video")
        self.kinect_group.addWidget(self.kinect_video_widget)
        self.kinect_depth_widget = QtWidgets.QWidget(self.widget)
        self.kinect_depth_widget.setObjectName("kinect_depth_widget")
        self.label_10 = QtWidgets.QLabel(self.kinect_depth_widget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.label_10.setObjectName("label_10")
        self.kinect_group.addWidget(self.kinect_depth_widget)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 500, 1291, 391))
        self.widget1.setObjectName("widget1")
        self.controlls = QtWidgets.QHBoxLayout(self.widget1)
        self.controlls.setContentsMargins(0, 0, 0, 0)
        self.controlls.setObjectName("controlls")
        self.locomotion_and_controls = QtWidgets.QHBoxLayout()
        self.locomotion_and_controls.setObjectName("locomotion_and_controls")
        self.locomotion = QtWidgets.QGroupBox(self.widget1)
        self.locomotion.setObjectName("locomotion")
        self.layoutWidget = QtWidgets.QWidget(self.locomotion)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.left_encoder_lcd = QtWidgets.QLCDNumber(self.layoutWidget)
        self.left_encoder_lcd.setObjectName("left_encoder_lcd")
        self.verticalLayout_5.addWidget(self.left_encoder_lcd)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.right_encoder_lcd = QtWidgets.QLCDNumber(self.layoutWidget)
        self.right_encoder_lcd.setObjectName("right_encoder_lcd")
        self.verticalLayout_4.addWidget(self.right_encoder_lcd)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.left_full = QtWidgets.QPushButton(self.layoutWidget)
        self.left_full.setMinimumSize(QtCore.QSize(50, 50))
        self.left_full.setMaximumSize(QtCore.QSize(0, 0))
        self.left_full.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app/client/gui/images/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_full.setIcon(icon)
        self.left_full.setIconSize(QtCore.QSize(45, 45))
        self.left_full.setObjectName("left_full")
        self.gridLayout.addWidget(self.left_full, 0, 0, 1, 1)
        self.forward = QtWidgets.QPushButton(self.layoutWidget)
        self.forward.setMinimumSize(QtCore.QSize(50, 50))
        self.forward.setMaximumSize(QtCore.QSize(0, 0))
        self.forward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("app/client/gui/images/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon1)
        self.forward.setIconSize(QtCore.QSize(45, 45))
        self.forward.setObjectName("forward")
        self.gridLayout.addWidget(self.forward, 0, 1, 1, 1)
        self.left = QtWidgets.QPushButton(self.layoutWidget)
        self.left.setMinimumSize(QtCore.QSize(50, 50))
        self.left.setMaximumSize(QtCore.QSize(0, 0))
        self.left.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("app/client/gui/images/round_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left.setIcon(icon2)
        self.left.setIconSize(QtCore.QSize(45, 45))
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 1, 0, 1, 1)
        self.backward = QtWidgets.QPushButton(self.layoutWidget)
        self.backward.setMinimumSize(QtCore.QSize(50, 50))
        self.backward.setMaximumSize(QtCore.QSize(0, 0))
        self.backward.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("app/client/gui/images/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backward.setIcon(icon3)
        self.backward.setIconSize(QtCore.QSize(45, 45))
        self.backward.setObjectName("backward")
        self.gridLayout.addWidget(self.backward, 1, 1, 1, 1)
        self.right = QtWidgets.QPushButton(self.layoutWidget)
        self.right.setMinimumSize(QtCore.QSize(50, 50))
        self.right.setMaximumSize(QtCore.QSize(0, 0))
        self.right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("app/client/gui/images/round_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right.setIcon(icon4)
        self.right.setIconSize(QtCore.QSize(45, 45))
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 1, 2, 1, 1)
        self.right_full = QtWidgets.QPushButton(self.layoutWidget)
        self.right_full.setMinimumSize(QtCore.QSize(50, 50))
        self.right_full.setMaximumSize(QtCore.QSize(0, 0))
        self.right_full.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("app/client/gui/images/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_full.setIcon(icon5)
        self.right_full.setIconSize(QtCore.QSize(45, 45))
        self.right_full.setObjectName("right_full")
        self.gridLayout.addWidget(self.right_full, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.motor_speed_cld = QtWidgets.QLCDNumber(self.layoutWidget)
        self.motor_speed_cld.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.motor_speed_cld.setProperty("intValue", 100)
        self.motor_speed_cld.setObjectName("motor_speed_cld")
        self.verticalLayout_2.addWidget(self.motor_speed_cld)
        self.motor_speed = QtWidgets.QDial(self.layoutWidget)
        self.motor_speed.setMaximum(255)
        self.motor_speed.setProperty("value", 100)
        self.motor_speed.setObjectName("motor_speed")
        self.verticalLayout_2.addWidget(self.motor_speed)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem3)
        self.locomotion_and_controls.addWidget(self.locomotion)
        self.turrent_controls = QtWidgets.QGroupBox(self.widget1)
        self.turrent_controls.setObjectName("turrent_controls")
        self.layoutWidget1 = QtWidgets.QWidget(self.turrent_controls)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 281, 356))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.turrent_encoder_lcd = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.turrent_encoder_lcd.setObjectName("turrent_encoder_lcd")
        self.verticalLayout_7.addWidget(self.turrent_encoder_lcd)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.color_sensor_lcd = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.color_sensor_lcd.setObjectName("color_sensor_lcd")
        self.verticalLayout_8.addWidget(self.color_sensor_lcd)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.turrent_left = QtWidgets.QPushButton(self.layoutWidget1)
        self.turrent_left.setMinimumSize(QtCore.QSize(50, 50))
        self.turrent_left.setMaximumSize(QtCore.QSize(0, 0))
        self.turrent_left.setText("")
        self.turrent_left.setIcon(icon2)
        self.turrent_left.setIconSize(QtCore.QSize(45, 45))
        self.turrent_left.setObjectName("turrent_left")
        self.gridLayout_2.addWidget(self.turrent_left, 0, 0, 1, 1)
        self.turrent_right = QtWidgets.QPushButton(self.layoutWidget1)
        self.turrent_right.setMinimumSize(QtCore.QSize(50, 50))
        self.turrent_right.setMaximumSize(QtCore.QSize(0, 0))
        self.turrent_right.setText("")
        self.turrent_right.setIcon(icon4)
        self.turrent_right.setIconSize(QtCore.QSize(45, 45))
        self.turrent_right.setObjectName("turrent_right")
        self.gridLayout_2.addWidget(self.turrent_right, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.turrent_speed_lcd = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.turrent_speed_lcd.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.turrent_speed_lcd.setProperty("intValue", 100)
        self.turrent_speed_lcd.setObjectName("turrent_speed_lcd")
        self.verticalLayout_3.addWidget(self.turrent_speed_lcd)
        self.turrent_speed = QtWidgets.QDial(self.layoutWidget1)
        self.turrent_speed.setMaximum(250)
        self.turrent_speed.setProperty("value", 99)
        self.turrent_speed.setObjectName("turrent_speed")
        self.verticalLayout_3.addWidget(self.turrent_speed)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.turrent_angle_lcd = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.turrent_angle_lcd.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.turrent_angle_lcd.setObjectName("turrent_angle_lcd")
        self.verticalLayout_11.addWidget(self.turrent_angle_lcd)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.turrent_angle = QtWidgets.QDial(self.layoutWidget1)
        self.turrent_angle.setMaximum(360)
        self.turrent_angle.setSliderPosition(180)
        self.turrent_angle.setObjectName("turrent_angle")
        self.horizontalLayout_6.addWidget(self.turrent_angle)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.turrent_reset = QtWidgets.QPushButton(self.layoutWidget1)
        self.turrent_reset.setObjectName("turrent_reset")
        self.verticalLayout_9.addWidget(self.turrent_reset)
        self.locomotion_and_controls.addWidget(self.turrent_controls)
        self.controlls.addLayout(self.locomotion_and_controls)
        self.other_sensors_and_controlls = QtWidgets.QHBoxLayout()
        self.other_sensors_and_controlls.setObjectName("other_sensors_and_controlls")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.video_options = QtWidgets.QGroupBox(self.widget1)
        self.video_options.setObjectName("video_options")
        self.layoutWidget2 = QtWidgets.QWidget(self.video_options)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 240, 141, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_video = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_video.setChecked(True)
        self.radioButton_video.setObjectName("radioButton_video")
        self.verticalLayout.addWidget(self.radioButton_video)
        self.radioButton_depth = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_depth.setObjectName("radioButton_depth")
        self.verticalLayout.addWidget(self.radioButton_depth)
        self.radioButton_cloud_point = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_cloud_point.setObjectName("radioButton_cloud_point")
        self.verticalLayout.addWidget(self.radioButton_cloud_point)
        self.groupBox_3 = QtWidgets.QGroupBox(self.video_options)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 40, 181, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter.setGeometry(QtCore.QRect(10, 50, 142, 50))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.robot_ip_address = QtWidgets.QLineEdit(self.splitter)
        self.robot_ip_address.setObjectName("robot_ip_address")
        self.connect_to_robot = QtWidgets.QPushButton(self.splitter)
        self.connect_to_robot.setObjectName("connect_to_robot")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_8.setObjectName("label_8")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(10, 120, 141, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_15.addWidget(self.video_options)
        self.other_sensors_and_controlls.addLayout(self.verticalLayout_15)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 81, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lcd_temperature = QtWidgets.QLCDNumber(self.layoutWidget3)
        self.lcd_temperature.setObjectName("lcd_temperature")
        self.verticalLayout_12.addWidget(self.lcd_temperature)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lcd_voltage = QtWidgets.QLCDNumber(self.layoutWidget3)
        self.lcd_voltage.setObjectName("lcd_voltage")
        self.verticalLayout_13.addWidget(self.lcd_voltage)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10, 180, 131, 81))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ultrasonic_sensor_lcd = QtWidgets.QLCDNumber(self.widget2)
        self.ultrasonic_sensor_lcd.setObjectName("ultrasonic_sensor_lcd")
        self.verticalLayout_16.addWidget(self.ultrasonic_sensor_lcd)
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.other_sensors_and_controlls.addWidget(self.groupBox_2)
        self.controlls.addLayout(self.other_sensors_and_controlls)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1307, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.motor_speed.valueChanged['int'].connect(self.motor_speed_cld.display)
        self.turrent_speed.valueChanged['int'].connect(self.turrent_speed_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kinect_video.setText(_translate("MainWindow", "video"))
        self.label_10.setText(_translate("MainWindow", "depth"))
        self.locomotion.setTitle(_translate("MainWindow", "locomotion"))
        self.label.setText(_translate("MainWindow", "left encoder"))
        self.label_2.setText(_translate("MainWindow", "right encoder"))
        self.left_full.setToolTip(_translate("MainWindow", "q"))
        self.left_full.setShortcut(_translate("MainWindow", "Q"))
        self.forward.setStatusTip(_translate("MainWindow", "w"))
        self.forward.setShortcut(_translate("MainWindow", "W"))
        self.left.setToolTip(_translate("MainWindow", "a"))
        self.left.setShortcut(_translate("MainWindow", "A"))
        self.backward.setToolTip(_translate("MainWindow", "s"))
        self.backward.setShortcut(_translate("MainWindow", "S"))
        self.right.setToolTip(_translate("MainWindow", "d"))
        self.right.setShortcut(_translate("MainWindow", "D"))
        self.right_full.setToolTip(_translate("MainWindow", "e"))
        self.right_full.setShortcut(_translate("MainWindow", "E"))
        self.turrent_controls.setTitle(_translate("MainWindow", "turrent"))
        self.label_3.setText(_translate("MainWindow", "turrent encoder"))
        self.label_4.setText(_translate("MainWindow", "color sensor"))
        self.turrent_left.setToolTip(_translate("MainWindow", "["))
        self.turrent_left.setShortcut(_translate("MainWindow", "["))
        self.turrent_right.setToolTip(_translate("MainWindow", "]"))
        self.turrent_right.setShortcut(_translate("MainWindow", "]"))
        self.label_5.setText(_translate("MainWindow", "turrent angle"))
        self.turrent_reset.setText(_translate("MainWindow", "turrent reset"))
        self.video_options.setTitle(_translate("MainWindow", "video options"))
        self.radioButton_video.setText(_translate("MainWindow", "Video"))
        self.radioButton_depth.setText(_translate("MainWindow", "Depth"))
        self.radioButton_cloud_point.setText(_translate("MainWindow", "Cloud Point"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Connection"))
        self.robot_ip_address.setText(_translate("MainWindow", "10.123.45.3"))
        self.connect_to_robot.setText(_translate("MainWindow", "connect"))
        self.label_8.setText(_translate("MainWindow", "Robot\'s IP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "sensors"))
        self.label_6.setText(_translate("MainWindow", "temp"))
        self.label_7.setText(_translate("MainWindow", "voltage"))
        self.label_9.setText(_translate("MainWindow", "ultrasound"))

